### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'sim'

### ISSUE THREAD

**Issue by dbailleul** [mitrefireline/simharness#1]
Hi everybody!
Thanks for releasing simHarness 1.0.0!

So I followed instructions to install simHarness with pyenv and poetry, I've created a ray cluster (ray start --num-gpus 1 --num-cpus 4 --head) and when I've typed "python3 main.py cli.mode=train" with original config.yaml (except for my own result path) and fire_harness.py modified to elude the circular importation of Harness, I've obtained this error:

```
(simharness3-py3.9) dbailleu@L-FRE-3KQMLX3:~/[...]/simharness$ python3 main.py cli.mode=train
2023-12-11 16:09:22,302 WARNING deprecation.py:50 -- DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future!
/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
 'allow_mutation' has been removed
  warnings.warn(message, UserWarning)
2023-12-11 16:09:23,296 WARNING deprecation.py:50 -- DeprecationWarning: `build_tf_policy` has been deprecated. This will raise an error in the future!
2023-12-11 16:09:23,298 WARNING deprecation.py:50 -- DeprecationWarning: `build_policy_class` has been deprecated. This will raise an error in the future!
2023-12-11 16:09:23,934 INFO worker.py:1431 -- Connecting to existing Ray cluster at address: 172.27.191.88:6379...
2023-12-11 16:09:23,940 INFO worker.py:1621 -- Connected to Ray cluster.
2023-12-11 16:09:24,312 INFO main.py:278 -- Configuration files for this job can be found at /home/dbailleu/[...]/data_dir/simharness/experiments/2023-12-11_16-09-23/hydra_output.
2023-12-11 16:09:24,328 INFO layers.py:81 -- Saving LandFire data to: /home/dbailleu/.simfire/landfire/2019/lf_120.52193_36.09493_120.47563370366066_36.04863370366067
2023-12-11 16:09:24,514 INFO layers.py:81 -- Saving LandFire data to: /home/dbailleu/.simfire/landfire/2019/lf_120.52193_36.09493_120.47563370366066_36.04863370366067
2023-12-11 16:09:24,592 INFO layers.py:81 -- Saving LandFire data to: /home/dbailleu/.simfire/landfire/2019/lf_120.52193_36.09493_120.47563370366066_36.04863370366067
2023-12-11 16:09:24,657 INFO layers.py:81 -- Saving LandFire data to: /home/dbailleu/.simfire/landfire/2019/lf_120.52193_36.09493_120.47563370366066_36.04863370366067
2023-12-11 16:09:24,756 WARNING algorithm_config.py:2558 -- Setting `exploration_config={}` because you set `_enable_rl_module_api=True`. When RLModule API are enabled, exploration_config can not be set. If you want to implement custom exploration behaviour, please modify the `forward_exploration` method of the RLModule at hand. On configs that have a default exploration config, this must be done with `config.exploration_config={}`.
/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/gymnasium/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:141: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be float32, actual type: float64
  logger.warn(
/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:165: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
2023-12-11 16:09:24,786 WARNING algorithm_config.py:2558 -- Setting `exploration_config={}` because you set `_enable_rl_module_api=True`. When RLModule API are enabled, exploration_config can not be set. If you want to implement custom exploration behaviour, please modify the `forward_exploration` method of the RLModule at hand. On configs that have a default exploration config, this must be done with `config.exploration_config={}`.
2023-12-11 16:09:24,803 WARNING deprecation.py:50 -- DeprecationWarning: `ignore_worker_failures is deprecated, and will soon be a no-op` has been deprecated. This will raise an error in the future!
2023-12-11 16:09:24,803 WARNING deprecation.py:50 -- DeprecationWarning: `AlgorithmConfig.rollouts(recreate_failed_workers=..)` has been deprecated. Use `AlgorithmConfig.fault_tolerance(recreate_failed_workers=..)` instead. This will raise an error in the future!
2023-12-11 16:09:24,803 WARNING deprecation.py:50 -- DeprecationWarning: `AlgorithmConfig.rollouts(restart_failed_sub_environments=..)` has been deprecated. Use `AlgorithmConfig.fault_tolerance(restart_failed_sub_environments=..)` instead. This will raise an error in the future!
2023-12-11 16:09:25,372 WARNING deprecation.py:50 -- DeprecationWarning: `rllib/algorithms/simple_q/` has been deprecated. Use `rllib_contrib/simple_q/` instead. This will raise an error in the future!
/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/utils/from_config.py:197: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `TBXLogger interface is deprecated in favor of the `ray.tune.tensorboardx.TBXLoggerCallback` interface and will be removed in Ray 2.7.
  object_ = constructor(*ctor_args, **ctor_kwargs)
(pid=32469) DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future!
(RolloutWorker pid=32469) /home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
(RolloutWorker pid=32469) * 'allow_mutation' has been removed
(RolloutWorker pid=32469)   warnings.warn(message, UserWarning)
(RolloutWorker pid=32469) 2023-12-11 16:09:30,906       WARNING deprecation.py:50 -- DeprecationWarning: `build_tf_policy` has been deprecated. This will raise an error in the future!
(RolloutWorker pid=32469) 2023-12-11 16:09:30,908       WARNING deprecation.py:50 -- DeprecationWarning: `build_policy_class` has been deprecated. This will raise an error in the future!
(RolloutWorker pid=32469) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32469, ip=172.27.191.88, actor_id=d31df7eb3a285eacb138b40f01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f2aa5c9a8e0>)
(RolloutWorker pid=32469)   File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
(RolloutWorker pid=32469)     self.env = env_creator(copy.deepcopy(self.env_context))
(RolloutWorker pid=32469)   File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda>
(RolloutWorker pid=32469)     register_env(cfg.environment.env, lambda config: env_cls(**config))
(RolloutWorker pid=32469) TypeError: __init__() got an unexpected keyword argument 'sim'
(pid=32580) DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future! [repeated 4x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RolloutWorker pid=32580) /home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2: [repeated 4x across cluster]
(RolloutWorker pid=32580) * 'allow_mutation' has been removed [repeated 4x across cluster]
(RolloutWorker pid=32580)   warnings.warn(message, UserWarning) [repeated 4x across cluster]
(RolloutWorker pid=32478) 2023-12-11 16:09:31,260       WARNING deprecation.py:50 -- DeprecationWarning: `build_tf_policy` has been deprecated. This will raise an error in the future! [repeated 3x across cluster]
(RolloutWorker pid=32478) 2023-12-11 16:09:31,262       WARNING deprecation.py:50 -- DeprecationWarning: `build_policy_class` has been deprecated. This will raise an error in the future! [repeated 3x across cluster]
(RolloutWorker pid=32580) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32580, ip=172.27.191.88, actor_id=2eeb5ab4963bb9aab2499d7d01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f065f58a8b0>) [repeated 4x across cluster]
(RolloutWorker pid=32580)   File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__ [repeated 4x across cluster]
(RolloutWorker pid=32580)     self.env = env_creator(copy.deepcopy(self.env_context)) [repeated 4x across cluster]
(RolloutWorker pid=32580)   File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda> [repeated 4x across cluster]
(RolloutWorker pid=32580)     register_env(cfg.environment.env, lambda config: env_cls(**config)) [repeated 4x across cluster]
(RolloutWorker pid=32580) TypeError: __init__() got an unexpected keyword argument 'sim' [repeated 4x across cluster]
2023-12-11 16:09:37,690 ERROR actor_manager.py:500 -- Ray error, taking actor 1 out of service. The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32469, ip=172.27.191.88, actor_id=d31df7eb3a285eacb138b40f01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f2aa5c9a8e0>)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda>
    register_env(cfg.environment.env, lambda config: env_cls(**config))
TypeError: __init__() got an unexpected keyword argument 'sim'
2023-12-11 16:09:37,690 ERROR actor_manager.py:500 -- Ray error, taking actor 2 out of service. The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32470, ip=172.27.191.88, actor_id=42fbe9f15ccfd1fbabfb21cc01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f94883e98e0>)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda>
    register_env(cfg.environment.env, lambda config: env_cls(**config))
TypeError: __init__() got an unexpected keyword argument 'sim'
2023-12-11 16:09:37,690 ERROR actor_manager.py:500 -- Ray error, taking actor 3 out of service. The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32477, ip=172.27.191.88, actor_id=ce012a1fe6e82ee1bac1e8f401000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f8d036728e0>)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda>
    register_env(cfg.environment.env, lambda config: env_cls(**config))
TypeError: __init__() got an unexpected keyword argument 'sim'
2023-12-11 16:09:37,691 ERROR actor_manager.py:500 -- Ray error, taking actor 4 out of service. The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32478, ip=172.27.191.88, actor_id=2d6bb8799851805e4df55d2e01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f3f0ceb2910>)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda>
    register_env(cfg.environment.env, lambda config: env_cls(**config))
TypeError: __init__() got an unexpected keyword argument 'sim'
2023-12-11 16:09:37,691 ERROR actor_manager.py:500 -- Ray error, taking actor 5 out of service. The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32580, ip=172.27.191.88, actor_id=2eeb5ab4963bb9aab2499d7d01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f065f58a8b0>)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda>
    register_env(cfg.environment.env, lambda config: env_cls(**config))
TypeError: __init__() got an unexpected keyword argument 'sim'
2023-12-11 16:09:37,691 ERROR actor_manager.py:500 -- Ray error, taking actor 6 out of service. The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32584, ip=172.27.191.88, actor_id=0410e303dd563ca1ce13eea001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fbd3ee8f8e0>)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda>
    register_env(cfg.environment.env, lambda config: env_cls(**config))
TypeError: __init__() got an unexpected keyword argument 'sim'
2023-12-11 16:09:37,691 ERROR actor_manager.py:500 -- Ray error, taking actor 7 out of service. The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32589, ip=172.27.191.88, actor_id=2d4a45925e6bb22f186add7a01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fca872ad8e0>)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda>
    register_env(cfg.environment.env, lambda config: env_cls(**config))
TypeError: __init__() got an unexpected keyword argument 'sim'
2023-12-11 16:09:37,691 ERROR actor_manager.py:500 -- Ray error, taking actor 8 out of service. The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32597, ip=172.27.191.88, actor_id=8c383224369e88932846e7ff01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f1defb5a940>)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda>
    register_env(cfg.environment.env, lambda config: env_cls(**config))
TypeError: __init__() got an unexpected keyword argument 'sim'
Error executing job with overrides: ['cli.mode=train']
Traceback (most recent call last):
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 157, in __init__
    self._setup(
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 227, in _setup
    self.add_workers(
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 593, in add_workers
    raise result.get()
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 481, in __fetch_result
    result = ray.get(r)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/_private/worker.py", line 2522, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32469, ip=172.27.191.88, actor_id=d31df7eb3a285eacb138b40f01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f2aa5c9a8e0>)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda>
    register_env(cfg.environment.env, lambda config: env_cls(**config))
TypeError: __init__() got an unexpected keyword argument 'sim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dbailleu/[...]/simharness/main.py", line 306, in <module>
    main()
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/dbailleu/[...]/simharness/main.py", line 284, in main
    algo = algo_cfg.build()
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm_config.py", line 1092, in build
    return algo_class(
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/utils/deprecation.py", line 106, in patched_init
    return obj_init(*args, **kwargs)
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 517, in __init__
    super().__init__(
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 639, in setup
    self.workers = WorkerSet(
  File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 179, in __init__
    raise e.args[0].args[2]
TypeError: __init__() got an unexpected keyword argument 'sim'
(pid=32597) DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future! [repeated 3x across cluster]
(RolloutWorker pid=32597) /home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2: [repeated 3x across cluster]
(RolloutWorker pid=32597) * 'allow_mutation' has been removed [repeated 3x across cluster]
(RolloutWorker pid=32597)   warnings.warn(message, UserWarning) [repeated 3x across cluster]
(RolloutWorker pid=32597) 2023-12-11 16:09:36,552       WARNING deprecation.py:50 -- DeprecationWarning: `build_tf_policy` has been deprecated. This will raise an error in the future! [repeated 4x across cluster]
(RolloutWorker pid=32597) 2023-12-11 16:09:36,553       WARNING deprecation.py:50 -- DeprecationWarning: `build_policy_class` has been deprecated. This will raise an error in the future! [repeated 4x across cluster]
(RolloutWorker pid=32597) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=32597, ip=172.27.191.88, actor_id=8c383224369e88932846e7ff01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f1defb5a940>) [repeated 3x across cluster]
(RolloutWorker pid=32597)   File "/home/dbailleu/[...]/simharness/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 397, in __init__ [repeated 3x across cluster]
(RolloutWorker pid=32597)     self.env = env_creator(copy.deepcopy(self.env_context)) [repeated 3x across cluster]
(RolloutWorker pid=32597)   File "/home/dbailleu/[...]/simharness/main.py", line 208, in <lambda> [repeated 3x across cluster]
(RolloutWorker pid=32597)     register_env(cfg.environment.env, lambda config: env_cls(**config)) [repeated 3x across cluster]
(RolloutWorker pid=32597) TypeError: __init__() got an unexpected keyword argument 'sim' [repeated 3x across cluster]
```

My own config is on WSL2 but I've also tried on my personal Linux computer: same error.
I have no idea how to solve this.
I just can say that there is a “sim” argument in the definition of EnvContext in reactive.py line 164 (and also marl_reactive.py but not relevant here).
There is no “sim” argument in the `__init__` of rollout_worker.py, but Envcontext is mentioned:
"validate_env: Optional[Callable[[EnvType, EnvContext], None]] = None," line 217 (file attached)
[rollout_worker.zip](https://github.com/mitrefireline/simharness/files/13637577/rollout_worker.zip)

No idea if it's helping.

Thanks a lot for simHarness and thanks for your help solving this!

**Comment by afennelly-mitre** [comment]
@dbailleul Thank you for the issue! My apologies on your experience so far with SimHarness. We are actively in the process of publishing our internal code here on GitHub, and there are a few more updates on the way before the code base is "ready to go". 

For a timeline, you can expect the state of SimHarness to be bug free come this Wednesday. Thank you for your patience!

**Comment by afennelly-mitre** [comment]
Hi @dbailleul, the updates in 56b6be8f2277019e2a8e5b8adf65a98f34b0d8e9 should resolve the issue (s) you are experiencing with SimHarness. Please make a new issue for any bugs, questions, comments, etc. as you use SimHarness. Thank you for the support!
